### ISSUE TITLE
The kitty icon in KDE shows a green tone

### ISSUE THREAD

**Issue by xulongwu4** [zayronxio/Zafiro-icons#105]
Hi, first of all, I really like your icons. Great work!

The issue I am seeing now is that the `kitty` icon shows a green-ish color tone in all KDE distributions I have tried, including Solus, KDE neon, and Garuda Linux. This is how the icon appears in the latte dock (it appears this way in all applications in KDE, such as the application menu):

![kitty_kde](https://user-images.githubusercontent.com/16892446/158456887-b75d9a0f-8e3f-4416-8564-51ee033735ec.png)

This is how it should look like:

![kitty_original](https://user-images.githubusercontent.com/16892446/158457034-5ffd1a10-5a19-4dd3-afe4-31864c0e02e9.png)

I have posted this question in reddit but was suggested to ask here to see if this is intentional behavior. Can you please suggest how I can make the icon appear with the correct color? Thanks a lot!

**Comment by jeois** [comment]
Sometimes KDE/Kwin shades its display objects differently.  For example, if you have "Night Color" on, it'll automatically shift the color temperature lower (more red, less blue).  Also, check System Settings>Appearance>Color to see if the color scheme makes a difference.  Perhaps something in Workspace Behavior>Desktop Effects might also be affecting it.

The only way to know for sure is to search for the icon image file (/usr/share/icons/Zafiro), using a file search app, and compare "kitty" to how it looks raw against how KDE presents it.  You might have to login temporarily into another Desktop Environment/Window Manager to make sure none of the effects KDE applies is affecting it.  If the icon is still green, then it was "intended".  (btw, mine is green also, but I don't mind and haven't checked thoroughly)

Many icon packs have colors for icons which are slightly different from their originals in order to fit with whatever color scheme its authors wanted.  Something like this, I'd chalk up to "creative differences" and just edit the icon myself if it really bothered me since it's only one icon.

Meanwhile, I also have an issue about using KDE with this icon set:  many of its '/actions' icons are presenting their light versions, even when the only option in KDE is the dark version (without switching its 'index.theme'), making it extremely difficult to see the icons in menus.  However, although it's related to color tones, this seems to a separate issue; so, I'll create another thread and explain what I did to try to fix it.

**Comment by xulongwu4** [comment]
@jeois, I think I have figured out why kitty icon does not show up correctly in KDE. It is the same as this issue: https://stackoverflow.com/questions/66907094/svg-color-problem-red-color-displayed-as-gray

It is indeed a bug in the icon itself. It used conflicting color declarations in the svg file of kitty. I am not sure though why this only happened to the kitty icon. I have not noticed this issue in any other program that I often use.

**Comment by jeois** [comment]
Nice, if you know how to edit it, you can copy your custom version to `home/~/.local/share/icons/Zafiro` and uninstall the package.  That's what I did for the `index.theme` issue #106 fixes, and how I handled the weather icon deletions.  

...because if I edit the system package directly (/usr/share/icons), it'll revert my fixes if there's an update or reinstall which doesn't address our issues.  Unfortunately, doing this prevents me from being notified through the AUR if this git project is updated.
