### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by WingofaGriffin** [zayronxio/Zafiro-icons#21]
Hello! Thank you for all the work. I still love it! Here are some more missing ones:

- Qalculate!
- [Write Stylus](http://www.styluslabs.com/)
- Anydesk
- Joplin
- Minetime

And also some broken symlinks for Budgie Desktop (because I'm difficult)

- OnlyOffice
- qBittorrent
- Nextcloud desktop sync client (Different than just Nextcloud)
- VLC
- MasterPDFEditor Free

Thank you so much!

**Comment by locomot1f** [comment]
I would also like to see updated icons for:
[] - LibreOffice
[] - Slack
[] - Station (getstation.com)

**Comment by tiotrom** [comment]
Some other that need an icon:
Cpod
Mindmapp
OpenSCAD
Celestia
Kstars
Stellarium
ClipGrab
ColorPicker
Copy Paste Grab
Imagine
MyPaint
Olive
Vorta
ApticGTK
Jitsi Meet
Private Internet Access
SYncthing
Etcher
Bookworm
Notable
Notes-up
Beaker Browser
FreeTube
GNU IceCat
Onionshare
Stremio
Tribler
Waterfox
Webtorrent
PhotoCollage
Cozy
Nuclear
Odio
Easystroke
Ambient Noise
Crow Translate
Opendesktop APP
Gnome Recipes
Spice-Up
Krop
Master PDF Editor
PDFSam

I am a webdesigner. How can I help with this? I can make svg's for many of them. Let me know please I am not familiar with how to contribute via github.

**Comment by zayronxio** [comment]
@tiotrom thank you for offering your help, if you do not want to use github you can send your icons to my email, zayronxio@gmail.com. thanks greetings

**Comment by tiotrom** [comment]
@zayronxio Great I already did a few I'll send the svgs to you ;)

**Comment by WingofaGriffin** [comment]
The icon pack seems to be have some issues with some ways you have symlinked the icons together in Budgie Desktop.

Additionally Brave Beta needs a symlink.

**Comment by zayronxio** [comment]
@tiotrom friend, will you send the icons you mentioned?

**Comment by tiotrom** [comment]
@zayronxio Yes sorry for the delay I was both busy with other projects but also I thought to maybe start a remix of this icon pack. Nevertheless I'll send you some stuff in a few hours.

**Comment by vtruong68** [comment]
I'd like to see a google drive icon if possible!

**Comment by medeotl** [comment]
Glade is missing icons, I guess both for the gtk3 and gtk2 version

**Comment by tiotrom** [comment]
I am reposting my list + a few more with the proper names for the icon files. We are making a custom Manjaro Gnome and we want to include your icons as default since they are amazing. So I am willing to spend more and more time reporting any missing ones and maybe even help out with some designs.

Name of the app - name of the icon file + URL of the app:

Anoise - anoise http://anoise.tuxfamily.org/
Cpod - cpod https://github.com/z-------------/CPod
Mindmapp - mindmapp https://aur.archlinux.org/packages/mindmapp
OpenSCAD - openscad https://www.openscad.org/
Celestia - celestia  www.shatters.net/celestia/
Etcher - balena-etcher-electron https://github.com/balena-io/etcher
Buka - buka https://github.com/oguzhaninan/Buka
Calibre - calibre https://calibre-ebook.com/
Clipgrab - (i could not find a way to replace their icon - i found clipgrab and clipgrab-kde but they dont seem to work) clipgrab.org
BookWorm - com.github.babluboy.bookworm https://babluboy.github.io/bookworm/
Fondo - com.github.calo001.fondo https://github.com/calo001/fondo
Ideogram - com.github.cassidyjames.ideogram https://github.com/cassidyjames/ideogram
Copypastegrab com.github.cryptowyrm.copypastegrab https://github.com/cryptowyrm/copypastegrab
cozy-audiobooks - com.github.geigi.cozy https://github.com/geigi/cozy
Notes Up - com.github.philip-scott.notes-up https://github.com/Philip-Scott/Notes-up
Spice-Up - com.github.philip-scott.spice-up https://github.com/Philip-Scott/Spice-up
Krop - edit-cut arminstraub.com/computer/krop
FreeTube - freetube https://github.com/FreeTubeApp/FreeTube
Gobby - gobby-0.5 https://gobby.github.io/
Icecat - icecat www.gnu.org/software/gnuzilla/
ipython2 - ipython2 ipython.org
java10-openjdk - java10-openjdk 
kid3 - kid3-qt https://kid3.sourceforge.io/
Kstars - kstars https://www.kde.org/applications/education/kstars/
MyPaint - mypaint http://mypaint.org/
Color Picker (gcolor3) - nl.hjdskes.gcolor3 https://www.hjdskes.nl/projects/gcolor3/
OpenDesktop App - opendesktop-app 
Gnome Recipes - org.gnome.Recipes https://wiki.gnome.org/Apps/Recipes
PDFSam - pdfsam www.pdfsam.org
Photocollage - photocollage https://github.com/adrienverge/PhotoCollage
Stellarium - stellarium http://stellarium.org/
Syncthing - syncthing-gtk https://github.com/syncthing/syncthing-gtk
Tribler - tribler https://www.tribler.org
VeraCrypt - veracrypt https://www.veracrypt.fr/
WaterFox - waterfox-icon https://www.waterfoxproject.org
WebTorrent - webtorrent-desktop https://webtorrent.io/desktop
Imagine  - ??? https://github.com/meowtec/Imagine/releases
Aptik GTK - aptik-gtk https://github.com/teejee2008/aptik-gtk
Jitsi Meet - ??? https://github.com/jitsi/jitsi-meet-electron
Private Internet Access - ???
Notable - notable https://github.com/fabiospampinato/notable
Beaker Browser - beaker-browser https://beakerbrowser.com
Onionshare - the icon path is /usr/share/pixmaps/onionshare80.xpm https://github.com/micahflee/onionshare
Stremio - smartcode-stremio https://www.stremio.com/
Odio - ???? https://github.com/odioapp/odio
Crow Translate - crow-translate https://github.com/Shatur95/crow-translate

Master PDF Editor

**Comment by medeotl** [comment]
problems also with text-x-python.svg, it works for python 2 but not for python3 (text-x-python3.svg)

**Comment by tiotrom** [comment]
A few more:

- synfig https://synfig.org

- Transmageddon Media Transcoder "transmageddon"  http://www.linuxrising.org/

- backintime "Icon=document-save" https://github.com/bit-team/backintime

- semantik "semantik" https://waf.io/semantik.html

- Mini Diary "????" https://github.com/samuelmeuli/mini-diary

- Qoob "qoob" https://gitlab.com/william.belanger/qoob

- Clipit "clipit-trayicon" https://github.com/CristianHenzel/ClipIt

- CopyQ "copyq"  https://github.com/hluk/CopyQ

- Raven Reader "raven-reader" https://github.com/mrgodhani/raven-reader/releases

**Comment by tiotrom** [comment]
First of all awesome to see so many new icons and please make a Liberapay account I want to support your work monthly :)

Ok let me add more applications that are missing icons:

- Celestia - celestia www.shatters.net/celestia/
- Kstars - kstars https://www.kde.org/applications/education/kstars/
- Ciano - com.github.robertsanseries.ciano.svg https://robertsanseries.github.io/ciano/
- Clipgrab - (i could not find a way to replace their icon - i found clipgrab and clipgrab-kde but they dont seem to work) https://clipgrab.org/
- Color Picker (gcolor3) - nl.hjdskes.gcolor3 https://www.hjdskes.nl/projects/gcolor3/
- Deepin Picker - deepin-picker.svg https://github.com/linuxdeepin/deepin-picker
- Jami - jami https://jami.net/
- Syncthing - syncthing-gtk https://github.com/syncthing/syncthing-gtk
- Buka - buka https://github.com/oguzhaninan/Buka
- Heimer 
- Notable - notable https://github.com/fabiospampinato/notable
- Icecat - icecat www.gnu.org/software/gnuzilla/
- VeraCrypt - veracrypt https://www.veracrypt.fr/
- Onionshare - the icon path is /usr/share/pixmaps/onionshare80.xpm https://github.com/micahflee/onionshare
- WebTorrent - webtorrent-desktop https://webtorrent.io/desktop
- Yarock - application-x-yarock https://seb-apps.github.io/yarock/
- Deepin Voice Recorder - deepin-voice-recorder https://github.com/linuxdeepin/deepin-voice-recorder
- FeedReader - org.gnome.FeedReader https://jangernert.github.io/FeedReader/
- Fondo - com.github.calo001.fondo https://github.com/calo001/fondo
- Gifcurry - com.lettier.gifcurry https://github.com/lettier/gifcurry
- PDF Tricks
-  Pomodoro (gnome-shell-pomodoro) gnome-pomodoro https://github.com/codito/gnome-pomodoro
- Krop - edit-cut http://arminstraub.com/software/krop

**Comment by zayronxio** [comment]
https://liberapay.com/Zayronxio
this is my liberapay account, I will soon update with more icons, greetings and thanks

**Comment by francoism90** [comment]
SMB4k is missing, but I'm happy if you could simple provide a symlink for it. :)

**Comment by Zeroneca** [comment]
Can someone make an icon for the Brave browser?

**Comment by WingofaGriffin** [comment]
Everybody, please check the files to see if the icon is actually implemented before asking for it. For example @Zeroneca Brave has an icon but you are having a simlink issue which requires more info.

That said, I would like icons for

- Xournalpp (simlink)
- uLauncher
- Fractal
- Yelp

I'm also having issues with the links on Cinnamon desktop with
- Joplin
- Preferred Applications
- Graphics Tablet

**Comment by tiotrom** [comment]
Freetube changed to freetube-bin and the icon has the same freetube-bin.png name. If you can update please :)

**Comment by WingofaGriffin** [comment]
Closing this issue as I am no longer using this pack.
