### ISSUE TITLE
Visual Studio Code icon

### ISSUE THREAD

**Issue by massimiliano-cannata** [zayronxio/Zafiro-icons#61]
Beautiful theme....
It would be nice to have also visual studio code icon

**Comment by allallston** [comment]
> It would be nice to have also visual studio code icon

They already have both "Visual Studio Code" and "Visual Studio Code Insiders" icons. You can close this issue. 
If you are not seeing the icons picked up, make sure your .desktop files reflect the correct icon designation. They should never be hard coded values because then the changes will not be applied when you select different icon themes. For example, here is what i use in my VSCode-Insiders .desktop file: `Icon=com.visualstudio.code.insiders`
