### ISSUE TITLE
Small icons in XFCE default to dark/black now

### ISSUE THREAD

**Issue by tio-trom** [zayronxio/Zafiro-icons#95]
Manjaro pushed a system update and for some reason the Zafiro icon is showcasing the small status icons as dark and whith a dark theme they are invisible:
![2021-11-21_13-38](https://user-images.githubusercontent.com/38043315/142762152-e638e0e6-1fa4-4031-b749-dc87205465e7.png)

If I were to make these icons bigger or smaller, between certain values, then they are shown as light. For example here I was selecting from zafiro's icon pack and i the selector the icons were one size, after I selected them, in the panel they were another. So I ended up selecting a light icon to then see it as dark icon. https://videos.trom.tf/w/6a1qSo1k7JCaKWRSU9NyjR

I think it is an issue with icon sizes. Can you look at this please :)

**Comment by zayronxio** [comment]
please try now

**Comment by tio-trom** [comment]
Funny because after the latest Manjaro update a few days ago it started to work again. Now after I tested the latest git version it is back ... 

![2021-12-20_14-32](https://user-images.githubusercontent.com/38043315/146774923-84084daf-af3d-43ce-ae0e-4abdd7f9e6dd.png)

Although the icons are a tiny bit more visible, they are still not ok. I wonder what's happening :)

**Comment by zayronxio** [comment]
issues solved

**Comment by jeois** [comment]
Thank you for creating this icon set.  They look great.  

However, I don't think this issue is solved.  I'm using KDE with this icon set:  many of its '/actions' icons are presenting their light versions, even when the only option in KDE is the dark version (without switching its 'index.theme'), making it extremely difficult to see the icons in menus.  

To fix this, I edited 'index.theme':

> 1) move 'hicolor' to the end of the _Inherits_ line
> 2) delete 'Numix-Circle-dark' ('Numix Circle' already defaults to dark, so the '-dark' directory is missing)
> 3) edit [actions/16] to [actions/16-Dark]

#3 is most important and probably does fix the bug; I would make a pull request, but I haven't used git in many years.  But, I'm still having some issues related to icons too dark for the background dark theme.  I'll report back if I have more info.
